# Initially copied from https://github.com/simonw/ca-fires-history/blob/d8f38a74b06fb7447bacec2c6e1bb524b2484099/.github/workflows/scrape.yml
# Many thanks to Simon Willison for refining and describing the technique of Git scraping.
# His excellent post on the topic: https://simonwillison.net/2020/Oct/9/git-scraping/

name: Scrape latest data

on:
  push:
  workflow_dispatch:
  #schedule:
  #  - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://am-i-eligible.covid19vaccine.health.ny.gov/api/list-providers \
          | jq 'del(.lastUpdated)' > appointment-availability.json
    - name: Commit and push if it changed
      run: |-
        DIFF=$(git diff)

        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
        
        echo "CHANGED=true" >> $GITHUB_ENV
        
        echo "DIFF<<EOF" >> $GITHUB_ENV
        echo "$DIFF" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Send email if it changed
      if: env.CHANGED == 'true'
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        to: avi@aviflax.com
        from: NY COVID Vaccination Appointment Scraper <ny-covid-vaccination-appointment-scraper@aviflax.com>
        subject: NY COVID Vaccination Appointment Availability Change
        convert_markdown: true
        body: |
          ```diff
          ${{env.DIFF}}
          ```
